- name: Create user
  hosts: vps
  remote_user: root
  gather_facts: no
  vars_files:
    - .env.yml
  roles:
    - role: user
      tags:
        - user

- name: Server setup
  hosts: vps
  remote_user: "{{ username }}"
  vars_files:
    - .env.yml

  roles:
    - role: harden
      become: true
      tags:
        - harden
        - sec

    - role: housekeeping
      become: true
      tags:
        - housekeeping

    - role: custom
      tags:
        - custom

    - role: nextcloud
      tags:
        - nextcloud
        - services

    - role: vault
      tags:
        - vault
        - services

    - role: searx
      tags:
        - searx
        - services

    - role: gitea
      tags:
        - gitea
        - services

    - role: website
      tags:
        - website

    - role: analytics
      tags:
        - analytics

    - role: onion
      become: true
      tags:
        - onion
        - website

    - role: fail2ban
      become: true
      tags:
        - fail2ban
        - sec

    - role: nginx
      become: true
      tags:
        - nginx

    - role: welcome
      become: true
      tags:
        - welcome

    - role: openvpn
      tags:
        - openvpn
