- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages:
      - "git"
      - "zsh"
      - "stow"

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/dotfiles"
    force: true

- name: Stow dotfiles
  args:
    chdir: "/home/{{ username }}/dotfiles"
  command:
    cmd: "stow -R ."
  changed_when: true
