- name: Nextcloud - Docker
  vars:
    container: "nextcloud"
    image: "nextcloud"
    data_dir: "/{{ service.nextcloud.subdomain }}-data"
    backup_dir: "{{ common_backup_dir }}/{{ service.nextcloud.subdomain }}"
  block:
    - import_tasks: setup.yml
    - import_tasks: run.yml
      tags: ignore-ci # TODO: docker in ci
    - import_tasks: maintenance.yml
